//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FallGuysStats.Resources {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FallGuysStats.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Bronze과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string details_bronze {
            get {
                return ResourceManager.GetString("details_bronze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Duration과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string details_duration {
            get {
                return ResourceManager.GetString("details_duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Eliminated과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string details_eliminated {
            get {
                return ResourceManager.GetString("details_eliminated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Final과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string details_final {
            get {
                return ResourceManager.GetString("details_final", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Final Stats과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string details_final_stats {
            get {
                return ResourceManager.GetString("details_final_stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Finish과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string details_finish {
            get {
                return ResourceManager.GetString("details_finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gold과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string details_gold {
            get {
                return ResourceManager.GetString("details_gold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kudos과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string details_kudos {
            get {
                return ResourceManager.GetString("details_kudos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Level과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string details_level {
            get {
                return ResourceManager.GetString("details_level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Level Stats과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string details_level_stats {
            get {
                return ResourceManager.GetString("details_level_stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pink과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string details_pink {
            get {
                return ResourceManager.GetString("details_pink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Players과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string details_players {
            get {
                return ResourceManager.GetString("details_players", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Position과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string details_position {
            get {
                return ResourceManager.GetString("details_position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove Shows과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string details_remove_shows {
            get {
                return ResourceManager.GetString("details_remove_shows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure you want to remove the selected {0} Shows?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string details_remove_shows_msg {
            get {
                return ResourceManager.GetString("details_remove_shows_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Round과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string details_round {
            get {
                return ResourceManager.GetString("details_round", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Round Stats과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string details_round_stats {
            get {
                return ResourceManager.GetString("details_round_stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rounds과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string details_rounds {
            get {
                return ResourceManager.GetString("details_rounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Score과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string details_score {
            get {
                return ResourceManager.GetString("details_score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string details_show {
            get {
                return ResourceManager.GetString("details_show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show Stats과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string details_show_stats {
            get {
                return ResourceManager.GetString("details_show_stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Silver과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string details_silver {
            get {
                return ResourceManager.GetString("details_silver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string details_start {
            get {
                return ResourceManager.GetString("details_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ALL TIME과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string overlay_all_time {
            get {
                return ResourceManager.GetString("overlay_all_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DAY과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string overlay_day {
            get {
                return ResourceManager.GetString("overlay_day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FASTEST과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string overlay_fastest {
            get {
                return ResourceManager.GetString("overlay_fastest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FINAL STREAK과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string overlay_final_streak {
            get {
                return ResourceManager.GetString("overlay_final_streak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GOLD과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string overlay_gold {
            get {
                return ResourceManager.GetString("overlay_gold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   HIGH SCORE과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string overlay_high_score {
            get {
                return ResourceManager.GetString("overlay_high_score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LONGEST과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string overlay_longest {
            get {
                return ResourceManager.GetString("overlay_longest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PING과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string overlay_ping {
            get {
                return ResourceManager.GetString("overlay_ping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PLAYERS과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string overlay_players {
            get {
                return ResourceManager.GetString("overlay_players", resourceCulture);
            }
        }
        
        /// <summary>
        ///   QUALIFY과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string overlay_qualify {
            get {
                return ResourceManager.GetString("overlay_qualify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ROUND과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string overlay_round {
            get {
                return ResourceManager.GetString("overlay_round", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SEASON과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string overlay_season {
            get {
                return ResourceManager.GetString("overlay_season", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SESSION과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string overlay_session {
            get {
                return ResourceManager.GetString("overlay_session", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TIME과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string overlay_time {
            get {
                return ResourceManager.GetString("overlay_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   WEEK과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string overlay_week {
            get {
                return ResourceManager.GetString("overlay_week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   WIN STREAK과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string overlay_win_streak {
            get {
                return ResourceManager.GetString("overlay_win_streak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Airtime과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string round_airtime {
            get {
                return ResourceManager.GetString("round_airtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Basketfall과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string round_basketfall {
            get {
                return ResourceManager.GetString("round_basketfall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Big Fans과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string round_big_fans {
            get {
                return ResourceManager.GetString("round_big_fans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Big Shots과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string round_big_shots {
            get {
                return ResourceManager.GetString("round_big_shots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Blast Ball과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string round_blast_ball {
            get {
                return ResourceManager.GetString("round_blast_ball", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Block Party과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string round_block_party {
            get {
                return ResourceManager.GetString("round_block_party", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bounce Party과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string round_bounce_party {
            get {
                return ResourceManager.GetString("round_bounce_party", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bubble Trouble과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string round_bubble_trouble {
            get {
                return ResourceManager.GetString("round_bubble_trouble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Button Bashers과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string round_button_bashers {
            get {
                return ResourceManager.GetString("round_button_bashers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dizzy Heights과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string round_dizzy_heights {
            get {
                return ResourceManager.GetString("round_dizzy_heights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Door Dash과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string round_door_dash {
            get {
                return ResourceManager.GetString("round_door_dash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Egg Scramble과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string round_egg_scramble {
            get {
                return ResourceManager.GetString("round_egg_scramble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Egg Siege과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string round_egg_siege {
            get {
                return ResourceManager.GetString("round_egg_siege", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fall Ball과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string round_fall_ball {
            get {
                return ResourceManager.GetString("round_fall_ball", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fall Mountain과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string round_fall_mountain {
            get {
                return ResourceManager.GetString("round_fall_mountain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Freezy Peak과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string round_freezy_peak {
            get {
                return ResourceManager.GetString("round_freezy_peak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fruit Chute과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string round_fruit_chute {
            get {
                return ResourceManager.GetString("round_fruit_chute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Full Tilt과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string round_full_tilt {
            get {
                return ResourceManager.GetString("round_full_tilt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gate Crash과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string round_gate_crash {
            get {
                return ResourceManager.GetString("round_gate_crash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hex-A-Gone과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string round_hex_a_gone {
            get {
                return ResourceManager.GetString("round_hex_a_gone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hex-A-Ring과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string round_hex_a_ring {
            get {
                return ResourceManager.GetString("round_hex_a_ring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hit Parade과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string round_hit_parade {
            get {
                return ResourceManager.GetString("round_hit_parade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hoarders과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string round_hoarders {
            get {
                return ResourceManager.GetString("round_hoarders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hoopsie Daisy과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string round_hoopsie_daisy {
            get {
                return ResourceManager.GetString("round_hoopsie_daisy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hoopsie Legends과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string round_hoopsie_legends {
            get {
                return ResourceManager.GetString("round_hoopsie_legends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hoverboard Heroes과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string round_hoverboard_heroes {
            get {
                return ResourceManager.GetString("round_hoverboard_heroes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Jinxed과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string round_jinxed {
            get {
                return ResourceManager.GetString("round_jinxed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Jump Club과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string round_jump_club {
            get {
                return ResourceManager.GetString("round_jump_club", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Jump Showdown과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string round_jump_showdown {
            get {
                return ResourceManager.GetString("round_jump_showdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Knight Fever과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string round_knight_fever {
            get {
                return ResourceManager.GetString("round_knight_fever", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Leading Light과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string round_leading_light {
            get {
                return ResourceManager.GetString("round_leading_light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lily Leapers과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string round_lily_leapers {
            get {
                return ResourceManager.GetString("round_lily_leapers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lost Temple과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string round_lost_temple {
            get {
                return ResourceManager.GetString("round_lost_temple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Party Promenade과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string round_party_promenade {
            get {
                return ResourceManager.GetString("round_party_promenade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pegwin Pool Party과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string round_pegwin_party {
            get {
                return ResourceManager.GetString("round_pegwin_party", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pegwin Pursuit과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string round_pegwin_pursuit {
            get {
                return ResourceManager.GetString("round_pegwin_pursuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Perfect Match과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string round_perfect_match {
            get {
                return ResourceManager.GetString("round_perfect_match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pipe Dream과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string round_pipe_dream {
            get {
                return ResourceManager.GetString("round_pipe_dream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Power Trip과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string round_power_trip {
            get {
                return ResourceManager.GetString("round_power_trip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rock&apos;N&apos;Roll과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string round_rock_n_roll {
            get {
                return ResourceManager.GetString("round_rock_n_roll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Roll Off과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string round_roll_off {
            get {
                return ResourceManager.GetString("round_roll_off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Roll On과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string round_roll_on {
            get {
                return ResourceManager.GetString("round_roll_on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Roll Out과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string round_roll_out {
            get {
                return ResourceManager.GetString("round_roll_out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Royal Fumble과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string round_royal_fumble {
            get {
                return ResourceManager.GetString("round_royal_fumble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   See Saw과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string round_see_saw {
            get {
                return ResourceManager.GetString("round_see_saw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Short Circuit과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string round_short_circuit {
            get {
                return ResourceManager.GetString("round_short_circuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ski Fall과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string round_ski_fall {
            get {
                return ResourceManager.GetString("round_ski_fall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Skyline Stumble과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string round_skyline_stumble {
            get {
                return ResourceManager.GetString("round_skyline_stumble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Slime Climb과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string round_slime_climb {
            get {
                return ResourceManager.GetString("round_slime_climb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Slimescraper과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string round_slimescraper {
            get {
                return ResourceManager.GetString("round_slimescraper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Snowball Survival과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string round_snowball_survival {
            get {
                return ResourceManager.GetString("round_snowball_survival", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Snowy Scrap과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string round_snowy_scrap {
            get {
                return ResourceManager.GetString("round_snowy_scrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Speed Circuit과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string round_speed_circuit {
            get {
                return ResourceManager.GetString("round_speed_circuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stompin&apos; Ground과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string round_stompin_ground {
            get {
                return ResourceManager.GetString("round_stompin_ground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sum Fruit과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string round_sum_fruit {
            get {
                return ResourceManager.GetString("round_sum_fruit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sweet Thieves과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string round_sweet_thieves {
            get {
                return ResourceManager.GetString("round_sweet_thieves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tail Tag과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string round_tail_tag {
            get {
                return ResourceManager.GetString("round_tail_tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Team Tail Tag과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string round_team_tail_tag {
            get {
                return ResourceManager.GetString("round_team_tail_tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The Swiveller과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string round_the_swiveller {
            get {
                return ResourceManager.GetString("round_the_swiveller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Thin Ice과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string round_thin_ice {
            get {
                return ResourceManager.GetString("round_thin_ice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tip Toe과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string round_tip_toe {
            get {
                return ResourceManager.GetString("round_tip_toe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Track Attack과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string round_track_attack {
            get {
                return ResourceManager.GetString("round_track_attack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Treetop Tumble과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string round_treetop_tumble {
            get {
                return ResourceManager.GetString("round_treetop_tumble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tundra Run과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string round_tundra_run {
            get {
                return ResourceManager.GetString("round_tundra_run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Volleyfall과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string round_volleyfall {
            get {
                return ResourceManager.GetString("round_volleyfall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wall Guys과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string round_wall_guys {
            get {
                return ResourceManager.GetString("round_wall_guys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Whirlygig과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string round_whirlygig {
            get {
                return ResourceManager.GetString("round_whirlygig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All Time Stats과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string settings_all_time_stats {
            get {
                return ResourceManager.GetString("settings_all_time_stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Black과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string settings_black {
            get {
                return ResourceManager.GetString("settings_black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Blue과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string settings_blue {
            get {
                return ResourceManager.GetString("settings_blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Day Stats과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string settings_day_stats {
            get {
                return ResourceManager.GetString("settings_day_stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exe files과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string settings_exe_files {
            get {
                return ResourceManager.GetString("settings_exe_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Green과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string settings_green {
            get {
                return ResourceManager.GetString("settings_green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Locate Fall Guys과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string settings_locate_fall_guys {
            get {
                return ResourceManager.GetString("settings_locate_fall_guys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Magenta과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string settings_magenta {
            get {
                return ResourceManager.GetString("settings_magenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Red과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string settings_red {
            get {
                return ResourceManager.GetString("settings_red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Season Stats과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string settings_season_stats {
            get {
                return ResourceManager.GetString("settings_season_stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Session Stats과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string settings_session_stats {
            get {
                return ResourceManager.GetString("settings_session_stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stats and Party Filter과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string settings_stats_and_party_filter {
            get {
                return ResourceManager.GetString("settings_stats_and_party_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Transparent과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string settings_transparent {
            get {
                return ResourceManager.GetString("settings_transparent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Week Stats과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string settings_week_stats {
            get {
                return ResourceManager.GetString("settings_week_stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wrong File Selected과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string settings_wrong_file_selected {
            get {
                return ResourceManager.GetString("settings_wrong_file_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please select &quot;FallGuys_client_game.exe&quot; in the install folder.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string settings_wrong_file_selected_msg {
            get {
                return ResourceManager.GetString("settings_wrong_file_selected_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Average과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string stats_average {
            get {
                return ResourceManager.GetString("stats_average", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bronze과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string stats_bronze {
            get {
                return ResourceManager.GetString("stats_bronze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fastest과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string stats_fastest {
            get {
                return ResourceManager.GetString("stats_fastest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Finals과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string stats_finals {
            get {
                return ResourceManager.GetString("stats_finals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gold과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string stats_gold {
            get {
                return ResourceManager.GetString("stats_gold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kudos과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string stats_kudos {
            get {
                return ResourceManager.GetString("stats_kudos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Level Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string stats_level_name {
            get {
                return ResourceManager.GetString("stats_level_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Longest과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string stats_longest {
            get {
                return ResourceManager.GetString("stats_longest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Played과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string stats_played {
            get {
                return ResourceManager.GetString("stats_played", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Qualified과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string stats_qualified {
            get {
                return ResourceManager.GetString("stats_qualified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rounds과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string stats_rounds {
            get {
                return ResourceManager.GetString("stats_rounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shows과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string stats_shows {
            get {
                return ResourceManager.GetString("stats_shows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Silver과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string stats_silver {
            get {
                return ResourceManager.GetString("stats_silver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Time Played과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string stats_time_played {
            get {
                return ResourceManager.GetString("stats_time_played", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wins과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string stats_wins {
            get {
                return ResourceManager.GetString("stats_wins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ui_error {
            get {
                return ResourceManager.GetString("ui_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error Updating과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ui_error_updating {
            get {
                return ResourceManager.GetString("ui_error_updating", resourceCulture);
            }
        }
    }
}
